{{- if and .Values.prometheusServiceMonitor.enabled .Values.optimize.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-optimize
  labels:
    {{- include "camundaPlatform.labels" . | nindent 4 }}
    app.kubernetes.io/version: {{ include "camundaPlatform.imageTagByParams" (dict "base" .Values.global "overlay" .Values.optimize) | quote }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
      app.kubernetes.io/component: optimize
  endpoints:
    - honorLabels: true
      path: {{ .Values.optimize.metrics.prometheus }}
      port: management
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
