{{- if and (.Values.global.identity.auth.enabled) (or (not .Values.global.identity.auth.operate.existingSecret) (typeIs "string" .Values.global.identity.auth.operate.existingSecret)) }}
{{- $secretName := include "identity.secretNameOptimizeIdentity" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "identity.labels" . | nindent 4 }}
type: Opaque
data:
  optimize-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "optimize-secret" "length" 10 "providedValues" (list "global.identity.auth.optimize.existingSecret") "context" $) }}
{{- end }}
