apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeebe.names.gateway" . }}
  labels: {{- include "zeebe.labels.gateway" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
    {{- toYaml  .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations}}
    {{ .Values.service.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 6 }}
  {{- end }}
  selector:
    {{- include "zeebe.matchLabels.gateway" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.httpPort }}
      protocol: TCP
      name: {{ default "http" .Values.service.httpName  }}
    - port: {{ .Values.service.gatewayPort }}
      protocol: TCP
      name: {{ default "gateway" .Values.service.gatewayName }}
