{{ if .Values.podDisruptionBudget.enabled  }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zeebe.names.gateway" . }}
  labels: {{- include "zeebe.labels.gateway" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zeebe.matchLabels.gateway" . | nindent 6 }}
{{ end }}
