{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zeebe.names.gateway" . }}
  labels: {{- include "zeebe.labels.gateway" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ tpl .Values.ingress.host $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "zeebe.names.gateway" . }}
                port:
                  number: {{ .Values.service.gatewayPort }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host $ }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
{{- end }}
